# Need to change YOUR_CLUSTER and YOUR_API_TOKEN accordingly

apiVersion: apps/v1
# Kubernetes versions after 1.9.0 should use apps/v1
# Kubernetes version 1.8.x should use apps/v1beta2
# Kubernetes versions before 1.8.0 should use apps/v1beta1
kind: Deployment
metadata:
  labels:
<<<<<<< HEAD
=======
<<<<<<< HEAD:deploy/src/services/10_wavefront.yaml
    app: $K8S_APPLICATION
    service: $K8S_NAMESPACE-wavefront-proxy
  name: $K8S_NAMESPACE-wavefront-proxy
  namespace: $K8S_NAMESPACE
=======
>>>>>>> wavefrontHQ-master
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: {{ .Values.namespace   }}-wavefront-proxy
  name: {{ .Values.namespace   }}-wavefront-proxy
  namespace: {{ .Values.namespace   }}
<<<<<<< HEAD
=======
>>>>>>> wavefrontHQ-master:deploy/helm/templates/10_wavefront.yaml
>>>>>>> wavefrontHQ-master
spec:
  replicas: 1
  selector:
    matchLabels:
<<<<<<< HEAD
=======
<<<<<<< HEAD:deploy/src/services/10_wavefront.yaml
      app: $K8S_APPLICATION
      service: $K8S_NAMESPACE-wavefront-proxy
  template:
    metadata:
      labels:
        app: $K8S_APPLICATION
        service: $K8S_NAMESPACE-wavefront-proxy
    spec:
      containers:
      - name: $K8S_NAMESPACE-wavefront-proxy
=======
>>>>>>> wavefrontHQ-master
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: {{ .Values.namespace   }}-wavefront-proxy
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: {{ .Values.namespace   }}-wavefront-proxy
    spec:
      containers:
      - name: {{ .Values.namespace   }}-wavefront-proxy
<<<<<<< HEAD
=======
>>>>>>> wavefrontHQ-master:deploy/helm/templates/10_wavefront.yaml
>>>>>>> wavefrontHQ-master
        image: projects.registry.vmware.com/tanzu_observability/proxy:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: WAVEFRONT_URL
<<<<<<< HEAD
          value: https://longboard.wavefront.com/api/
=======
          value: {{ .Values.wavefront.url }}
>>>>>>> wavefrontHQ-master
        - name: WAVEFRONT_TOKEN
          valueFrom:
            secretKeyRef:
              name: wf-token
              key: token
        # Uncomment the below lines to consume Zipkin/Istio traces
        - name: WAVEFRONT_PROXY_ARGS
          value: --traceListenerPorts 30000
        ports:
        - containerPort: 2878
          protocol: TCP
        # Uncomment the below lines to consume traces
        - containerPort: 30000
          protocol: TCP
        securityContext:
          privileged: false
---
apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
=======
<<<<<<< HEAD:deploy/src/services/10_wavefront.yaml
  name: $K8S_NAMESPACE-wavefront-proxy
  namespace: $K8S_NAMESPACE
  labels:
    app: $K8S_APPLICATION
    service: $K8S_NAMESPACE-wavefront-proxy
=======
>>>>>>> wavefrontHQ-master
  name: {{ .Values.namespace   }}-wavefront-proxy
  namespace: {{ .Values.namespace   }}
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: {{ .Values.namespace   }}-wavefront-proxy
<<<<<<< HEAD
=======
>>>>>>> wavefrontHQ-master:deploy/helm/templates/10_wavefront.yaml
>>>>>>> wavefrontHQ-master
spec:
  ports:
  - name: wavefront
    port: 2878
    protocol: TCP
  - name: http
    port: 30000
    targetPort: 30000
    protocol: TCP
  selector:
<<<<<<< HEAD
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: {{ .Values.namespace   }}-wavefront-proxy
=======
<<<<<<< HEAD:deploy/src/services/10_wavefront.yaml
    app: $K8S_APPLICATION
    service: $K8S_NAMESPACE-wavefront-proxy
=======
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: {{ .Values.namespace   }}-wavefront-proxy
>>>>>>> wavefrontHQ-master:deploy/helm/templates/10_wavefront.yaml
>>>>>>> wavefrontHQ-master
