---
apiVersion: v1
kind: Service
metadata:
  name: shopping
  namespace: {{ .Values.namespace   }}
spec: 
  selector:
    application: {{ .Release.Name  }}
    service: shopping
  type: LoadBalancer
  ports:
  - name: application
    port: 50050
  - name: admin
    port: 50150
