apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    service: styling
    shard: blue
  name: styling-blue
  namespace: sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandbox
      service: styling
      shard: blue
  template:
    metadata:
      labels:
        app: sandbox
        service: styling
        shard: blue
    spec:
      containers:
      - name: styling
        image: wfharbor.eng.vmware.com/demo-app/styling:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/styling.jar"
        - "server"
        - "/conf/styling-app.yaml"
        ports:
        - containerPort: 50051
          name: application
          protocol: TCP
        - containerPort: 50151
          name: admin
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    service: styling
    shard: green
  name: styling-green
  namespace: sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandbox
      service: styling
      shard: green
  template:
    metadata:
      labels:
        app: sandbox
        service: styling
        shard: green
    spec:
      containers:
        - name: styling
          image: wfharbor.eng.vmware.com/demo-app/styling:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/styling.jar"
            - "server"
            - "/conf/styling-app.yaml"
          ports:
            - containerPort: 50051
              name: application
              protocol: TCP
            - containerPort: 50151
              name: admin
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: styling
  namespace: sandbox
spec: 
  selector:
    app: sandbox
    service: styling  
  type: ClusterIP
  ports:
  - name: application
    port: 50051
  - name: admin
    port: 50151

