apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    service: notification
    shard: blue
  name: notification-blue
  namespace: sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandbox
      service: notification
      shard: blue
  template:
    metadata:
      labels:
        app: sandbox
        service: notification
        shard: blue
    spec:
      containers:
      - name: notification
        image: wfharbor.eng.vmware.com/demo-app/notification:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/notification.jar"
        - "--spring.config.location=/conf/notification-app.yml"
        ports:
        - containerPort: 50056
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    service: notification
    shard: green
  name: notification-green
  namespace: sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sandbox
      service: notification
      shard: green
  template:
    metadata:
      labels:
        app: sandbox
        service: notification
        shard: green
    spec:
      containers:
        - name: notification
          image: wfharbor.eng.vmware.com/demo-app/notification:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/notification.jar"
            - "--spring.config.location=/conf/notification-app.yml"
          ports:
            - containerPort: 50056
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: sandbox
spec: 
  selector:
    app: sandbox
    service: notification  
  type: ClusterIP
  ports:
  - name: application
    port: 50056

