apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    service: warehouse
    shard: blue
  name: warehouse-blue
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
      service: warehouse
      shard: blue
  template:
    metadata:
      labels:
        app: sandbox
        service: warehouse
        shard: blue
    spec:
      containers:
      - name: warehouse
        image: wfharbor.eng.vmware.com/demo-app/warehouse:latest
        imagePullPolicy: Always
        command:
        - "python3"
        - "manage.py"
        - "runserver"
        - "0.0.0.0:50060"
        ports:
        - containerPort: 50060
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox
    service: warehouse
    shard: green
  name: warehouse-green
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
      service: warehouse
      shard: green
  template:
    metadata:
      labels:
        app: sandbox
        service: warehouse
        shard: green
    spec:
      containers:
        - name: warehouse
          image: wfharbor.eng.vmware.com/demo-app/warehouse:latest
          imagePullPolicy: Always
          command:
            - "python3"
            - "manage.py"
            - "runserver"
            - "0.0.0.0:50060"
          ports:
            - containerPort: 50060
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse
  namespace: sandbox
spec: 
  selector:
    app: sandbox
    service: warehouse
  type: ClusterIP
  ports:
  - name: application
    port: 50060

