version: '2'

services:
  wavefront-proxy:
    image: projects.registry.vmware.com/tanzu_observability/proxy:latest
    container_name: wavefront-proxy
    environment: 
      - WAVEFRONT_URL=https://longboard.wavefront.com/api
      - WAVEFRONT_TOKEN=dc9fed86-6875-4cad-8cb2-c4ddd60360c4
      - WAVEFRONT_PROXY_ARGS= --customTracingListenerPorts 30000  --customMessageTags log

  printing:
    image: ${K8S_REPOSITORY}printing
    container_name: printing
    volumes:
      - ./../data/:/conf/
    command:
      - "java"
      - "-jar"
      - "/printing.jar"
      - "/conf/printing-app.yaml"


  packaging:
    image: ${K8S_REPOSITORY}packaging
    container_name: packaging
    volumes:
      - ./../data/:/conf/
    command:
      - "java"
      - "-jar"
      - "/packaging.jar"
      - "/conf/packaging-app.yaml"

  notification:
    image: ${K8S_REPOSITORY}notification
    container_name: notfication
    volumes:
      - ./../data/:/conf/
    command:
      - "java"
      - "-jar"
      - "/notification.jar"
      - "--spring.config.location=/conf/notification-app.yaml"

  warehouse:
    image: ${K8S_REPOSITORY}warehouse
    container_name: warehouse
    volumes:
      - ./../data/:/conf/
    command:
      - "python3"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:50060"

  payments:
    image: ${K8S_REPOSITORY}payments
    container_name: payments
    volumes:
      - ./../data/:/conf/
    command:
      - "dotnet"
      - "run"
      - "--no-build"
      - "-p"
      - "/payments/src/Payments/"

  delivery:
    image: ${K8S_REPOSITORY}delivery
    container_name: delivery
    volumes:
      - ./../data/:/conf/
    command:
      - "java"
      - "-jar"
      - "/delivery.jar"
      - "--spring.config.location=/conf/delivery-app.yaml"
    mem_limit: 1024M
    depends_on:
     - notification

  inventory:
    image: ${K8S_REPOSITORY}inventory
    container_name: inventory
    volumes:
      - ./../data/:/conf/
    command: /inventory /conf/inventory.conf
    depends_on:
      - warehouse

  styling:
    image: ${K8S_REPOSITORY}styling
    container_name: styling
    volumes:
      - ./../data/:/conf/
    command:
      - "java"
      - "-jar"
      - "/styling.jar"
      - "server"
      - "/conf/styling-app.yaml"
    depends_on:
      - printing
      - packaging
      
  shopping:
    image: ${K8S_REPOSITORY}shopping
    container_name: shopping
    volumes:
      - ./../data/:/conf/
    command:
     - "java"
     - "-jar"
     - "/shopping.jar"
     - "server"
     - "/conf/shopping-app.yaml"
    ports:
     - 50050:50050
     - 50150:50150
    depends_on:
      - delivery
      - payments
      - inventory
      - styling
      - wavefront-proxy

  loadgen:
    image: ${K8S_REPOSITORY}loadgen
    command:
      - "java"
      - "-jar"
      - "/loadgen.jar"
      - "shopping"
      - "50050"
      - "50051"
      - "2"
      - "15"
      - "0"
